ame: Deploy to ECR

on:

  push:
    branches: [ master ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Prepare tags
      id: prepare-tags
      run: |
        DOCKER_IMAGE=${{ secrets.ECR_URL }}/testing-terraform-docker
        VERSION=latest
        TAGS="${DOCKER_IMAGE}:${VERSION}"
        if [ "${{ github.event_name }}" = "push" ]; then
          VERSION=sha-${GITHUB_SHA}
          TAGS="$TAGS,${DOCKER_IMAGE}:${VERSION}"
        fi
        echo ::set-output name=tags::${TAGS}
        echo ::set-output name=deploy-version::${VERSION}

    - name: Push image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.prepare-tags.outputs.tags }}
